---
- apt: name={{item}}
  with_items:
    - git-core
    - python
    - python-cheetah
  sudo: yes

- git: repo=http://github.com/midgetspy/Sick-Beard.git dest=/root/sickbeard
  sudo: yes

- copy: src=nginx_config dest=/etc/nginx/sites-available/sickbeard
  sudo: yes

- file: src=/etc/nginx/sites-available/sickbeard dest=/etc/nginx/sites-enabled/sickbeard state=link
  sudo: yes
  notify: restart nginx
