---
- apt: name=nginx update_cache=yes
  sudo: yes

- name: Ensures nginx html dir exists
  file: path=/var/www/html/ state=directory

- name: Install dashboard
  template: src=index.html.j2 dest=/var/www/html/index.html
  sudo: yes
  notify: restart nginx

- name: Install dashboard
  copy: src={{item}} dest=/var/www/html/{{item}}
  with_items:
    - jquery.js
    - main.js
    - main.css
  sudo: yes
  notify: restart nginx
