---
- apt_key: keyserver=keyserver.ubuntu.com id='0xFDA5DFFC' keyring='/etc/apt/trusted.gpg' state=present
  sudo: yes

- apt_repository: repo='deb http://apt.sonarr.tv/ master main' state=present
  sudo: yes

- apt: name=nzbdrone update_cache=yes
  sudo: yes

- copy: src=init_d dest=/etc/init.d/nzbdrone mode=0744
  sudo: yes
  notify: start nzbdrone

- user: name=nzbdrone home=/var/lib/nzbdrone group=nogroup createhome=yes
  sudo: yes

- service: name=nzbdrone enabled=yes
  sudo: yes
  notify: start nzbdrone

- copy: src=nginx_config dest=/etc/nginx/sites-available/sonarr
  sudo: yes

- file: src=/etc/nginx/sites-available/sonarr dest=/etc/nginx/sites-enabled/sonarr state=link
  sudo: yes
  notify: restart nginx
